version: "3"
networks:
  app-network: null
services:
  nginx:
    image: "nginx:stable-alpine"
    container_name: "nginx_${APP_NAME}"
    ports:
      - "80:80"
    volumes:
      - "./src:/var/www/html"
      - "./nginx-default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php
      - mysql
    networks:
      - app-network
  mysql:
    image: "mysql:5.7.22"
    container_name: "mysql_${APP_NAME}"
    restart: unless-stopped
    tty: true
    command: --sql_mode=''
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      SERVICE_TAGS: "${SERVICE_TAGS}"
      SERVICE_NAME: "${SERVICE_NAME}"
    networks:
      - app-network
  php:
    image: php:7.4-fpm-alpine
    container_name: "php_${APP_NAME}"
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - "./src:/var/www/html"
    ports:
      - "9000:9000"
    networks:
      - app-network